
# Set variables
variables:
  adp_path: '/adp'  

trigger:
- main
- develop
- uat
- features/*
- hotfix/*
- release/*

pool: AZP-Pool

steps:
- bash: 'pytest --junitxml=$(Build.StagingDirectory)/sample1.xml' 
  workingDirectory: 'test'
  displayName: 'Run test sample1'

- task: PublishTestResults@2
  displayName: 'Publish test result sample1.xml'
  inputs:
    testResultsFiles: '$(Build.StagingDirectory)/sample1.xml'
    testRunTitle: Sample1

