
# Set variables
variables:
  adp_path: '/adp'  

trigger:
- main
- develop
- uat
- features/*
- hotfix/*
- release/*

  # strategy:
  #   matrix:
  #     Python35:
  #       python.version: '3.5'
  #     Python36:
  #       python.version: '3.6'
  #     Python37:
  #       python.version: '3.7'

pool: AZP-Pool

steps:
  # - task: UsePythonVersion@0
  #   displayName: 'Use Python $(python.version)'
  #   inputs:
  #     versionSpec: '$(python.version)'
  # 
- bash: 'pytest --junitxml=$(Build.StagingDirectory)/sample1.xml' 
  workingDirectory: 'test'
  displayName: 'Run test sample1'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish test result sample1.xml'
  inputs:
    testResultsFiles: '$(Build.StagingDirectory)/sample1.xml'
    testRunTitle: Sample1

